site_name: Wiki
nav:
  - Home: index.md
  - Mkdocs: mkdocs.md
  - DevInitConfig: webDevInit.md
  - MeterialUI: materialUI.md
  - React: react.md
  - JavaScript: javascript.md
  - ReactNative: react-native.md
theme: readthedocs
